language: node_js
node_js:
- '10'
before_install:
- npm install -g @angular/cli
install: npm install
branches:
  only:
  - master
deploy:
  provider: heroku
  app: ng-toodoo
  api_key:
    secure: 4fJIt2/Ef9ivUe86f3G4bYNEGWV+EU2k1YDzgNUO9YMgrw0j4wBOIQQ/Yypd1IvSTfTHbhjtx/L0AfAmfxkGJAP3mV0WAXfW0UT9RhA1L7Axa8ogx4QDRBVqApRdZHdzz2xv7GynAzc7xB2kUFzbdM5bQPzzPkIwqqV7U4eiUecOCe93pQ2NTE8FPvoZNyiJqB3uzV7BdUlY9qxFdEpynJUvIZ6Wn6eyLEGNfrL5VxTFUvbgNxbnb2GKQazfAsqTScUldUJeALs/3HwhGTHTM0Mofho8IwMc8KNCulCPmEIsLqeTcll9w2wiAycGYRrw3qMtP1W+79sKRudkVg3adeGYgKT/orAv6kLsuBKymgXBWcbP0FiHF9xXaN7HaC1ZpmfKasIrZ9mM8gIZPA9mUUcNJIOYoVdeydHfEmUWCjF2LVR7MnvxfATx6zykcmqaxz5Xgk+X4h9rFx4sA+1XB/ImI4GGRb5KJiTiaya1JgS/DezkqzlsqJEoyy/Adg+CZPaP756DT9NgRYMuujDDH/iloAcQWCxmc8ZPLPDepgUYGIEKBtOM6qJr0iDUnllWyQhSBkrQrfAzPTPDHFRrd1shv4WNbjsdicqCgReN+wPczyPyrwgDv55MN/XwwMdOysuNA8uJgPNzFs18hZ7zktiecbpyiCIMDHucbo78ZZI=
